
import type { Yacht } from './types';

export const featuredYachts: Yacht[] = [
  {
    id: '2',
    name: 'Ocean Voyager',
    boatType: 'Sailing',
    listingType: 'Private',
    price: 850000,
    year: 2020,
    length: 60,
    location: 'Newport, RI',
    locationId: 'newport',
    imageUrl: 'https://placehold.co/600x400/34495E/FFFFFF.png',
    imageHint: 'sailing yacht',
    make: "Nautor's Swan",
    model: 'Swan 60',
    condition: 'Used',
    images: ['https://placehold.co/600x400/34495E/FFFFFF.png'],
    description: 'A performance cruiser with elegant lines and a powerful sail plan. Perfect for both competitive racing and comfortable blue-water cruising. Well-maintained by a single owner.',
    fuelType: 'diesel',
    hullMaterial: 'composite',
  },
  {
    id: '5',
    name: 'Wind Whisperer',
    boatType: 'Sailing',
    listingType: 'Private',
    price: 480000,
    year: 2019,
    length: 45,
    location: 'Santorini, Greece',
    locationId: 'santorini',
    imageUrl: 'https://placehold.co/600x400/E0E0E0/363636.png',
    imageHint: 'sailboat sunset',
    make: 'Beneteau',
    model: 'Oceanis 45',
    condition: 'Used',
    images: ['https://placehold.co/600x400/E0E0E0/363636.png'],
    description: 'The ideal Mediterranean cruiser. This Beneteau Oceanis 45 is easy to handle, comfortable, and has been lovingly cared for. Equipped with solar panels and a water maker for extended cruising.',
    fuelType: 'diesel',
    hullMaterial: 'fiberglass',
  },
  {
    id: '9',
    name: 'Gale Force',
    boatType: 'Sailing',
    listingType: 'Broker',
    price: 650000,
    year: 2018,
    length: 52,
    location: 'Auckland, NZ',
    locationId: 'auckland',
    imageUrl: 'https://placehold.co/600x400/581845/FFC300.png',
    imageHint: 'racing sailboat',
    make: 'Hanse',
    model: '508',
    condition: 'Used',
    images: ['https://placehold.co/600x400/581845/FFC300.png'],
    description: 'A fast and comfortable cruiser from Hanse. Known for its easy-to-handle self-tacking jib and spacious, modern interior. Ready for coastal hopping or offshore passages.',
    fuelType: 'diesel',
    hullMaterial: 'fiberglass',
  },
  {
    id: '1',
    name: 'Serenity Cruiser',
    boatType: 'Sailing',
    listingType: 'Broker',
    price: 1250000,
    year: 2022,
    length: 75,
    location: 'Miami, FL',
    locationId: 'miami',
    imageUrl: 'https://placehold.co/600x400/A2B9D1/34495E.png',
    imageHint: 'modern yacht',
    make: 'Benetti',
    model: 'Oasis 40M',
    condition: 'Used',
    images: [
      'https://placehold.co/600x400/a2b9d1/34495E.png',
      'https://placehold.co/600x400/a2b9d2/34495E.png',
      'https://placehold.co/600x400/a2b9d3/34495E.png',
      'https://placehold.co/600x400/a2b9d4/34495E.png',
      'https://placehold.co/600x400/a2b9d5/34495E.png',
      'https://placehold.co/600x400/a2b9d6/34495E.png',
    ],
    description: 'A stunning example of modern yacht design, offering unparalleled luxury and comfort. Features a spacious open-plan layout, a beach club at the stern, and state-of-the-art navigation systems.',
    fuelType: 'diesel',
    hullMaterial: 'fiberglass',
  },
  {
    id: '3',
    name: 'Twin Hull Drifter',
    boatType: 'Catamaran',
    listingType: 'Broker',
    price: 975000,
    year: 2023,
    length: 55,
    location: 'Fort Lauderdale, FL',
    locationId: 'fort-lauderdale',
    imageUrl: 'https://placehold.co/600x400/4ECCA3/232931.png',
    imageHint: 'catamaran boat',
    make: 'Lagoon',
    model: '55',
    condition: 'New',
    images: ['https://placehold.co/600x400/4ECCA3/232931.png'],
    description: 'Brand new Lagoon 55 offering incredible volume and stability. The expansive flybridge and forward cockpit are perfect for entertaining. Ready for immediate delivery.',
    fuelType: 'diesel',
    hullMaterial: 'fiberglass',
    usageStyles: ['catamaran'],
  },
];

export const priceValues = [
    '10000', '20000', '30000', '40000', '50000', '60000', '70000', '80000', '90000', '100000',
    '150000', '200000', '250000', '300000', '350000', '400000', '450000', '500000',
    '750000', '1000000', '1500000', '2000000', '3000000', '5000000', '10000000'
];

export const boatTypes = [
  { id: 'sailing', label: 'Sailing' },
];

export const usageStyles = [
  { id: 'monohull', label: 'Monohull' },
  { id: 'catamaran', label: 'Catamaran' },
  { id: 'expedition', label: 'Expedition' },
  { id: 'bluewater-passage', label: 'Bluewater Passage' },
  { id: 'off-shore', label: 'Off Shore' },
  { id: 'in-shore', label: 'In Shore' },
  { id: 'island', label: 'Island' },
  { id: 'off-grid', label: 'Off Grid' },
  { id: 'project', label: 'Project' },
];

export const makes = [
  { id: '2-bar', value: '2-bar', label: '2 Bar' },
  { id: '3b-craft', value: '3b-craft', label: '3B Craft' },
  { id: '3d-craft', value: '3d-craft', label: '3D Craft' },
  { id: '3d-tender', value: '3d-tender', label: '3D Tender' },
  { id: 'a-m-manufacturing', value: 'a-m-manufacturing', label: 'A&M Manufacturing' },
  { id: 'ab', value: 'ab', label: 'AB' },
  { id: 'ab-inflatables', value: 'ab-inflatables', label: 'AB Inflatables' },
  { id: 'abd', value: 'abd', label: 'ABD' },
  { id: 'acb', value: 'acb', label: 'ACB' },
  { id: 'acm', value: 'acm', label: 'ACM' },
  { id: 'aes-yacht', value: 'aes-yacht', label: 'AES Yacht' },
  { id: 'alk2-powerboats', value: 'alk2-powerboats', label: 'ALK2 Powerboats' },
  { id: 'amp', value: 'amp', label: 'AMP' },
  { id: 'atx-surf-boats', value: 'atx-surf-boats', label: 'ATX Surf Boats' },
  { id: 'abacus', value: 'abacus', label: 'Abacus' },
  { id: 'abati-yachts', value: 'abati-yachts', label: 'Abati Yachts' },
  { id: 'abeking-rasmussen', value: 'abeking-rasmussen', label: 'Abeking & Rasmussen' },
  { id: 'abim', value: 'abim', label: 'Abim' },
  { id: 'absolute', value: 'absolute', label: 'Absolute' },
  { id: 'accelera', value: 'accelera', label: 'Accelera' },
  { id: 'achilles', value: 'achilles', label: 'Achilles' },
  { id: 'acico', value: 'acico', label: 'Acico' },
  { id: 'action', value: 'action', label: 'Action' },
  { id: 'action-craft', value: 'action-craft', label: 'Action Craft' },
  { id: 'activator', value: 'activator', label: 'Activator' },
  { id: 'active-thunder', value: 'active-thunder', label: 'Active Thunder' },
  { id: 'ada-yacht', value: 'ada-yacht', label: 'Ada Yacht' },
  { id: 'adagio', value: 'adagio', label: 'Adagio' },
  { id: 'admiral', value: 'admiral', label: 'Admiral' },
  { id: 'admiralstender', value: 'admiralstender', label: 'AdmiralsTender' },
  { id: 'adonia', value: 'adonia', label: 'Adonia' },
  { id: 'advantage', value: 'advantage', label: 'Advantage' },
  { id: 'aegean-yacht', value: 'aegean-yacht', label: 'Aegean Yacht' },
  { id: 'aeon-marine', value: 'aeon-marine', label: 'Aeon Marine' },
  { id: 'africat-marine', value: 'africat-marine', label: 'Africat Marine' },
  { id: 'agapi', value: 'agapi', label: 'Agapi' },
  { id: 'agena-marin', value: 'agena-marin', label: 'Agena Marin' },
  { id: 'agilis', value: 'agilis', label: 'Agilis' },
  { id: 'aiata', value: 'aiata', label: 'Aiata' },
  { id: 'aicon', value: 'aicon', label: 'Aicon' },
  { id: 'airboat', value: 'airboat', label: 'Airboat' },
  { id: 'airon', value: 'airon', label: 'Airon' },
  { id: 'airship', value: 'airship', label: 'Airship' },
  { id: 'al-dhaen', value: 'al-dhaen', label: 'Al Dhaen' },
  { id: 'al-rubban-marine', value: 'al-rubban-marine', label: 'Al Rubban Marine' },
  { id: 'alalunga', value: 'alalunga', label: 'Alalunga' },
  { id: 'alaska', value: 'alaska', label: 'Alaska' },
  { id: 'alaskan', value: 'alaskan', label: 'Alaskan' },
  { id: 'albatro', value: 'albatro', label: 'Albatro' },
  { id: 'albatross', value: 'albatross', label: 'Albatross' },
  { id: 'albemarle', value: 'albemarle', label: 'Albemarle' },
  { id: 'albin', value: 'albin', label: 'Albin' },
  { id: 'albury-brothers', value: 'albury-brothers', label: 'Albury Brothers' },
  { id: 'alden', value: 'alden', label: 'Alden' },
  { id: 'alen', value: 'alen', label: 'Alen' },
  { id: 'alena', value: 'alena', label: 'Alena' },
  { id: 'alfamarine', value: 'alfamarine', label: 'Alfamarine' },
  { id: 'alfastreet', value: 'alfastreet', label: 'Alfastreet' },
  { id: 'alglas', value: 'alglas', label: 'Alglas' },
  { id: 'alia-yachts', value: 'alia-yachts', label: 'Alia Yachts' },
  { id: 'allsea', value: 'allsea', label: 'AllSea' },
  { id: 'allseas', value: 'allseas', label: 'Allseas' },
  { id: 'allures', value: 'allures', label: 'Allures' },
  { id: 'alm', value: 'alm', label: 'Alm' },
  { id: 'almar', value: 'almar', label: 'Almar' },
  { id: 'almarine', value: 'almarine', label: 'Almarine' },
  { id: 'aloha', value: 'aloha', label: 'Aloha' },
  { id: 'alpa', value: 'alpa', label: 'Alpa' },
  { id: 'alpha', value: 'alpha', label: 'Alpha' },
  { id: 'alson', value: 'alson', label: 'Alson' },
  { id: 'altair', value: 'altair', label: 'Altair' },
  { id: 'altamar', value: 'altamar', label: 'Altamar' },
  { id: 'altena', value: 'altena', label: 'Altena' },
  { id: 'altima', value: 'altima', label: 'Altima' },
  { id: 'alubat', value: 'alubat', label: 'Alubat' },
  { id: 'alumacat', value: 'alumacat', label: 'AlumaCat' },
  { id: 'alumacraft', value: 'alumacraft', label: 'Alumacraft' },
  { id: 'alumaweld', value: 'alumaweld', label: 'Alumaweld' },
  { id: 'aluminum-cruiser', value: 'aluminum-cruiser', label: 'Aluminum Cruiser' },
  { id: 'aluva', value: 'aluva', label: 'Aluva' },
  { id: 'alweld', value: 'alweld', label: 'Alweld' },
  { id: 'amarès', value: 'amarès', label: 'Amarès' },
  { id: 'amel', value: 'amel', label: 'Amel' },
  { id: 'amels', value: 'amels', label: 'Amels' },
  { id: 'amer', value: 'amer', label: 'Amer' },
  { id: 'ameracat', value: 'ameracat', label: 'AmeraCat' },
  { id: 'american-marine', value: 'american-marine', label: 'American Marine' },
  { id: 'american-tug', value: 'american-tug', label: 'American Tug' },
  { id: 'anderson', value: 'anderson', label: 'Anderson' },
  { id: 'andrews', value: 'andrews', label: 'Andrews' },
  { id: 'andros', value: 'andros', label: 'Andros' },
  { id: 'angel', value: 'angel', label: 'Angel' },
  { id: 'angler', value: 'angler', label: 'Angler' },
  { id: 'antago', value: 'antago', label: 'Antago' },
  { id: 'antonini-navi', value: 'antonini-navi', label: 'Antonini Navi' },
  { id: 'anvera', value: 'anvera', label: 'Anvera' },
  { id: 'anytec', value: 'anytec', label: 'Anytec' },
  { id: 'apache', value: 'apache', label: 'Apache' },
  { id: 'apex', value: 'apex', label: 'Apex' },
  { id: 'apex-yachts', value: 'apex-yachts', label: 'Apex Yachts' },
  { id: 'apollo', value: 'apollo', label: 'Apollo' },
  { id: 'apollonian-yachts', value: 'apollonian-yachts', label: 'Apollonian Yachts' },
  { id: 'apreamare', value: 'apreamare', label: 'Apreamare' },
  { id: 'aqua', value: 'aqua', label: 'Aqua' },
  { id: 'aquabat', value: 'aquabat', label: 'Aquabat' },
  { id: 'aquabell', value: 'aquabell', label: 'AquaBell' },
  { id: 'aquador', value: 'aquador', label: 'Aquador' },
  { id: 'aqualine', value: 'aqualine', label: 'Aqualine' },
  { id: 'aquanaut', value: 'aquanaut', label: 'Aquanaut' },
  { id: 'aquapatio', value: 'aquapatio', label: 'AquaPatio' },
  { id: 'aquapro', value: 'aquapro', label: 'Aquapro' },
  { id: 'aquascan', value: 'aquascan', label: 'Aquascan' },
  { id: 'aquasport', value: 'aquasport', label: 'Aquasport' },
  { id: 'aquastar', value: 'aquastar', label: 'Aquastar' },
  { id: 'aquatron', value: 'aquatron', label: 'Aquatron' },
  { id: 'aquila', value: 'aquila', label: 'Aquila' },
  { id: 'aquitalia', value: 'aquitalia', label: 'Aquitalia' },
  { id: 'aqvaboats', value: 'aqvaboats', label: 'Aqvaboats' },
  { id: 'arcadia-yachts', value: 'arcadia-yachts', label: 'Arcadia Yachts' },
  { id: 'archipelago', value: 'archipelago', label: 'Archipelago' },
  { id: 'arcoa', value: 'arcoa', label: 'Arcoa' },
  { id: 'arctic-blue', value: 'arctic-blue', label: 'Arctic Blue' },
  { id: 'aresa', value: 'aresa', label: 'Aresa' },
  { id: 'areys-pond', value: 'areys-pond', label: "Arey's Pond" },
  { id: 'argo', value: 'argo', label: 'Argo' },
  { id: 'argo-navis', value: 'argo-navis', label: 'Argo Navis' },
  { id: 'argonaut', value: 'argonaut', label: 'Argonaut' },
  { id: 'arima', value: 'arima', label: 'Arima' },
  { id: 'arimar', value: 'arimar', label: 'Arimar' },
  { id: 'arkos', value: 'arkos', label: 'Arkos' },
  { id: 'arksen', value: 'arksen', label: 'Arksen' },
  { id: 'armon', value: 'armon', label: 'Armon' },
  { id: 'armstrong-marine', value: 'armstrong-marine', label: 'Armstrong Marine' },
  { id: 'arno-leopard', value: 'arno-leopard', label: 'Arno Leopard' },
  { id: 'aron', value: 'aron', label: 'Aron' },
  { id: 'arran', value: 'arran', label: 'Arran' },
  { id: 'arrowcat', value: 'arrowcat', label: 'ArrowCat' },
  { id: 'artaban', value: 'artaban', label: 'Artaban' },
  { id: 'arvor', value: 'arvor', label: 'Arvor' },
  { id: 'askeladden', value: 'askeladden', label: 'Askeladden' },
  { id: 'aspen', value: 'aspen', label: 'Aspen' },
  { id: 'aspre', value: 'aspre', label: 'Aspre' },
  { id: 'asterie', value: 'asterie', label: 'Asterie' },
  { id: 'astilleros', value: 'astilleros', label: 'Astilleros' },
  { id: 'astinor', value: 'astinor', label: 'Astinor' },
  { id: 'astondoa', value: 'astondoa', label: 'Astondoa' },
  { id: 'atak-yachts', value: 'atak-yachts', label: 'Atak Yachts' },
  { id: 'atlante', value: 'atlante', label: 'Atlante' },
  { id: 'atlantic', value: 'atlantic', label: 'Atlantic' },
  { id: 'atlantis', value: 'atlantis', label: 'Atlantis' },
  { id: 'atlas-boat-works', value: 'atlas-boat-works', label: 'Atlas Boat Works' },
  { id: 'atollvic', value: 'atollvic', label: 'Atollvic' },
  { id: 'aurea', value: 'aurea', label: 'Aurea' },
  { id: 'aurora', value: 'aurora', label: 'Aurora' },
  { id: 'austal', value: 'austal', label: 'Austal' },
  { id: 'auster', value: 'auster', label: 'Auster' },
  { id: 'austin-parker', value: 'austin-parker', label: 'Austin Parker' },
  { id: 'ava-yachts', value: 'ava-yachts', label: 'AvA Yachts' },
  { id: 'avalon', value: 'avalon', label: 'Avalon' },
  { id: 'avance', value: 'avance', label: 'Avance' },
  { id: 'avanti', value: 'avanti', label: 'Avanti' },
  { id: 'avenger', value: 'avenger', label: 'Avenger' },
  { id: 'aventura', value: 'aventura', label: 'Aventura' },
  { id: 'aviara', value: 'aviara', label: 'Aviara' },
  { id: 'avid', value: 'avid', label: 'Avid' },
  { id: 'avila', value: 'avila', label: 'Avila' },
  { id: 'avon', value: 'avon', label: 'Avon' },
  { id: 'axis', value: 'axis', label: 'Axis' },
  { id: 'axopar', value: 'axopar', label: 'Axopar' },
  { id: 'ayros', value: 'ayros', label: 'Ayros' },
  { id: 'azov', value: 'azov', label: 'Azov' },
  { id: 'azure', value: 'azure', label: 'Azure' },
  { id: 'azzurro', value: 'azzurro', label: 'Azzurro' },
].sort((a, b) => a.label.localeCompare(b.label));

export const locationsByRegion = [
    {
        region: 'North America',
        locations: [
            { id: 'seattle', label: 'Seattle, WA', subRegion: 'North' },
            { id: 'vancouver', label: 'Vancouver, BC', subRegion: 'North' },
            { id: 'san-diego', label: 'San Diego, CA', subRegion: 'West' },
            { id: 'los-angeles', label: 'Los Angeles, CA', subRegion: 'West' },
            { id: 'miami', label: 'Miami, FL', subRegion: 'East' },
            { id: 'newport', label: 'Newport, RI', subRegion: 'East' },
            { id: 'fort-lauderdale', label: 'Fort Lauderdale, FL', subRegion: 'East' },
            { id: 'annapolis', label: 'Annapolis, MD', subRegion: 'East' },
        ],
    },
    {
        region: 'Europe',
        locations: [
            { id: 'oslo', label: 'Oslo, Norway', subRegion: 'North' },
            { id: 'london', label: 'London, UK', subRegion: 'North' },
            { id: 'monaco', label: 'Monaco', subRegion: 'South' },
            { id: 'santorini', label: 'Santorini, Greece', subRegion: 'South' },
            { id: 'palma', label: 'Palma de Mallorca', subRegion: 'South' },
            { id: 'lisbon', label: 'Lisbon, Portugal', subRegion: 'West' },
        ],
    },
    {
        region: 'Africa',
        locations: [],
    },
    {
        region: 'South America',
        locations: [
            { id: 'cancun', label: 'Cancun, Mexico', subRegion: 'North' },
            { id: 'cartagena', label: 'Cartagena, Colombia', subRegion: 'North' },
            { id: 'rio', label: 'Rio de Janeiro, Brazil', subRegion: 'East' },
        ],
    },
    {
        region: 'Asia',
        locations: [
            { id: 'dubai', label: 'Dubai, UAE', subRegion: 'West' },
            { id: 'phuket', label: 'Phuket, Thailand', subRegion: 'East' },
            { id: 'singapore', label: 'Singapore', subRegion: 'East' },
        ],
    },
    {
        region: 'Australia',
        locations: [
            { id: 'cairns', label: 'Cairns', subRegion: 'North' },
            { id: 'hobart', label: 'Hobart', subRegion: 'South' },
            { id: 'sydney', label: 'Sydney', subRegion: 'East' },
            { id: 'perth', label: 'Perth', subRegion: 'West' },
        ],
    },
    {
        region: 'New Zealand',
        locations: [
            { id: 'auckland', label: 'Auckland', subRegion: 'North' },
            { id: 'wellington', label: 'Wellington', subRegion: 'South' },
        ],
    },
];

export const conditions = [
  { id: 'new', label: 'New' },
  { id: 'used', label: 'Used' },
];

export const listingTypes = [
  { id: 'private', label: 'Private' },
  { id: 'broker', label: 'Broker' },
];

export const fuelTypes = [
  { id: 'diesel', label: 'Diesel' },
  { id: 'gas', label: 'Gasoline' },
  { id: 'electric', label: 'Electric' },
];

export const hullMaterialOptions = [
  { id: 'fiberglass', label: 'Fiberglass' },
  { id: 'aluminum', label: 'Aluminum' },
  { id: 'steel', label: 'Steel' },
  { id: 'wood', label: 'Wood' },
  { id: 'composite', label: 'Composite' },
];

export const hullShapeOptions = [
    { id: 'displacement', label: 'Displacement' },
    { id: 'semi-displacement', label: 'Semi-Displacement' },
    { id: 'planing', label: 'Planing' },
    { id: 'catamaran', label: 'Catamaran' },
    { id: 'trimaran', label: 'Trimaran' },
];

export const bowShapeOptions = [
    { id: 'plumb', label: 'Plumb' },
    { id: 'raked', label: 'Raked' },
    { id: 'spoon', label: 'Spoon' },
    { id: 'clipper', label: 'Clipper' },
    { id: 'reverse', label: 'Reverse/Wave-Piercing' },
];

export const keelTypeOptions = [
    { id: 'full', label: 'Full Keel' },
    { id: 'fin', label: 'Fin Keel' },
    { id: 'winged', label: 'Winged Keel' },
    { id: 'bulb', label: 'Bulb Keel' },
    { id: 'daggerboard', label: 'Daggerboard' },
];

export const rudderTypeOptions = [
    { id: 'skeg-hung', label: 'Skeg-Hung' },
    { id: 'spade', label: 'Spade' },
    { id: 'transom-hung', label: 'Transom-Hung' },
    { id: 'keel-hung', label: 'Keel-Hung' },
];

export const propellerTypeOptions = [
    { id: 'fixed-pitch', label: 'Fixed-Pitch' },
    { id: 'folding', label: 'Folding' },
    { id: 'feathering', label: 'Feathering' },
    { id: 'controllable-pitch', label: 'Controllable-Pitch' },
];


export const featureOptions = [
    { id: 'gps', label: 'GPS Navigation' },
    { id: 'autopilot', label: 'Autopilot System' },
    { id: 'radar', label: 'Radar' },
    { id: 'airConditioning', label: 'Air Conditioning' },
    { id: 'heating', label: 'Heating' },
    { id: 'generator', label: 'Generator' },
    { id: 'bowThruster', label: 'Bow Thruster' },
    { id: 'sternThruster', label: 'Stern Thruster' },
    { id: 'waterMaker', label: 'Water Maker' },
    { id: 'inverter', label: 'Inverter' },
    { id: 'solarPanels', label: 'Solar Panels' },
    { id: 'dinghy', label: 'Dinghy Included' },
].sort((a, b) => a.label.localeCompare(b.label));

export const deckOptions = [
    { id: 'teak-deck', label: 'Teak Deck' },
    { id: 'dodger', label: 'Dodger' },
    { id: 'bimini', label: 'Bimini Top' },
    { id: 'cockpit-table', label: 'Cockpit Table' },
    { id: 'cockpit-shower', label: 'Cockpit Shower' },
    { id: 'electric-winch', label: 'Electric Winch' },
    { id: 'wheel-steering', label: 'Wheel Steering' },
    { id: 'tiller-steering', label: 'Tiller Steering' },
    { id: 'windlass', label: 'Electric Windlass' },
    { id: 'swim-platform', label: 'Swim Platform' },
].sort((a, b) => a.label.localeCompare(b.label));

export const cabinOptions = [
    { id: 'nav-station', label: 'Navigation Station' },
    { id: 'galley-fridge', label: 'Refrigerator' },
    { id: 'galley-freezer', label: 'Freezer' },
    { id: 'galley-oven', label: 'Oven' },
    { id: 'microwave', label: 'Microwave' },
    { id: 'cabin-fans', label: 'Cabin Fans' },
    { id: 'electric-head', label: 'Electric Head' },
    { id: 'manual-head', label: 'Manual Head' },
    { id: 'hot-water', label: 'Hot Water System' },
    { id: 'tv-set', label: 'TV Set' },
].sort((a, b) => a.label.localeCompare(b.label));
