import type { Yacht } from './types';

export const featuredYachts: Yacht[] = [
  {
    id: 1,
    name: 'Serenity Cruiser',
    type: 'Motor',
    price: 1250000,
    year: 2022,
    length: 75,
    location: 'Miami, FL',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'modern yacht',
  },
  {
    id: 2,
    name: 'Ocean Voyager',
    type: 'Sailing',
    price: 850000,
    year: 2020,
    length: 60,
    location: 'Newport, RI',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sailing yacht',
  },
  {
    id: 3,
    name: 'Twin Hull Drifter',
    type: 'Catamaran',
    price: 975000,
    year: 2023,
    length: 55,
    location: 'Fort Lauderdale, FL',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'catamaran boat',
  },
  {
    id: 4,
    name: 'Azure Dream',
    type: 'Motor',
    price: 2500000,
    year: 2021,
    length: 90,
    location: 'Monaco',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'luxury yacht',
  },
  {
    id: 5,
    name: 'Wind Whisperer',
    type: 'Sailing',
    price: 480000,
    year: 2019,
    length: 45,
    location: 'Santorini, Greece',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sailboat sunset',
  },
  {
    id: 6,
    name: 'Coastal Runner',
    type: 'Motor',
    price: 720000,
    year: 2022,
    length: 50,
    location: 'San Diego, CA',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fast yacht',
  },
];
