
import * as z from 'zod';

export const sellFormSchema = z.object({
  title: z.string().optional(),
  make: z.string().optional(),
  model: z.string().optional(),
  year: z.coerce.number().optional().nullable(),
  length: z.coerce.number().optional().nullable(),
  price: z.coerce.number().optional().nullable(),
  description: z.string().optional(),
  heroImage: z.any().optional(),
  galleryImages: z.array(z.any()).optional(),
  listingType: z.string().optional(),
  boatType: z.string().optional(),
  condition: z.string().optional(),
  location: z.string().optional(),
  fuelType: z.string().optional(),
  hullMaterial: z.string().optional(),
  transomShape: z.string().optional(),
  bowShape: z.string().optional(),
  keelType: z.string().optional(),
  rudderType: z.string().optional(),
  propellerType: z.string().optional(),
  sailRigging: z.string().optional(),
  features: z.array(z.string()).optional(),
  divisions: z.array(z.string()).optional(),
  deck: z.array(z.string()).optional(),
  otherSpecifications: z.string().optional(),

  // General Information
  loaM: z.coerce.number().optional().nullable(),
  lwlM: z.coerce.number().optional().nullable(),
  beamM: z.coerce.number().optional().nullable(),
  draftM: z.coerce.number().optional().nullable(),
  airDraftM: z.coerce.number().optional().nullable(),
  headroomM: z.coerce.number().optional().nullable(),
  country: z.string().optional().nullable(),
  designer: z.string().optional().nullable(),
  displacementT: z.coerce.number().optional().nullable(),
  ballastTonnes: z.coerce.number().optional().nullable(),
  hullColor: z.string().optional().nullable(),
  hullShape: z.string().optional().nullable(),
  superstructureMaterial: z.string().optional().nullable(),
  deckMaterial: z.string().optional().nullable(),
  deckFinish: z.string().optional().nullable(),
  superstructureDeckFinish: z.string().optional().nullable(),
  cockpitDeckFinish: z.string().optional().nullable(),
  dorades: z.string().optional().nullable(),
  windowFrame: z.string().optional().nullable(),
  windowMaterial: z.string().optional().nullable(),
  deckhatch: z.string().optional().nullable(),
  fuelTankLitre: z.coerce.number().optional().nullable(),
  levelIndicatorFuel: z.string().optional().nullable(),
  freshwaterTankLitre: z.coerce.number().optional().nullable(),
  levelIndicatorFreshwater: z.string().optional().nullable(),
  wheelSteering: z.string().optional().nullable(),
  outsideHelmPosition: z.string().optional().nullable(),

  // Accommodation
  accommodation: z.object({
    numberOfCabins: z.coerce.number().optional().nullable(),
    numberOfBerths: z.coerce.number().optional().nullable(),
    interiorMaterial: z.string().optional().nullable(),
    layout: z.string().optional().nullable(),
    floor: z.string().optional().nullable(),
    openCockpit: z.boolean().optional().nullable(),
    aftDeck: z.boolean().optional().nullable(),
    saloonHeadroom: z.coerce.number().optional().nullable(),
    heating: z.string().optional().nullable(),
    navigationCenter: z.boolean().optional().nullable(),
    chartTable: z.boolean().optional().nullable(),
    countertop: z.string().optional().nullable(),
    sink: z.string().optional().nullable(),
    cooker: z.string().optional().nullable(),
    oven: z.string().optional().nullable(),
    microwave: z.string().optional().nullable(),
    fridge: z.string().optional().nullable(),
    freezer: z.string().optional().nullable(),
    hotWaterSystem: z.string().optional().nullable(),
    waterPressureSystem: z.string().optional().nullable(),
    ownersCabin: z.string().optional().nullable(),
    ownersCabinBedLength: z.string().optional().nullable(),
    ownersCabinWardrobe: z.string().optional().nullable(),
    ownersCabinBathroom: z.string().optional().nullable(),
    ownersCabinToilet: z.string().optional().nullable(),
    ownersCabinToiletSystem: z.string().optional().nullable(),
    ownersCabinWashBasin: z.string().optional().nullable(),
    ownersCabinShower: z.string().optional().nullable(),
    guestCabin1: z.string().optional().nullable(),
    guestCabin1BedLength: z.string().optional().nullable(),
    guestCabin1Wardrobe: z.string().optional().nullable(),
    guestCabin2: z.string().optional().nullable(),
    guestCabin2BedLength: z.string().optional().nullable(),
    guestCabin2Wardrobe: z.string().optional().nullable(),
    sharedBathroom: z.string().optional().nullable(),
    sharedToilet: z.string().optional().nullable(),
    sharedToiletSystem: z.string().optional().nullable(),
    sharedWashBasin: z.string().optional().nullable(),
    sharedShower: z.string().optional().nullable(),
    washingMachine: z.string().optional().nullable(),
    cabins: z.array(z.string()).optional().nullable(),
    saloon: z.array(z.string()).optional().nullable(),
    galley: z.array(z.string()).optional().nullable(),
    heads: z.array(z.string()).optional().nullable(),
  }).optional().nullable(),

  // Rigging
  rigging: z.object({
    rigging: z.string().optional().nullable(),
    standingRigging: z.string().optional().nullable(),
    brandMast: z.string().optional().nullable(),
    materialMast: z.string().optional().nullable(),
    spreaders: z.string().optional().nullable(),
    mainsail: z.string().optional().nullable(),
    stowayMast: z.string().optional().nullable(),
    cutterstay: z.string().optional().nullable(),
    jib: z.string().optional().nullable(),
    genoa: z.string().optional().nullable(),
    genoaFurler: z.string().optional().nullable(),
    cutterFurler: z.string().optional().nullable(),
    gennaker: z.string().optional().nullable(),
    spinnaker: z.string().optional().nullable(),
    reefingSystem: z.string().optional().nullable(),
    backstayAdjuster: z.string().optional().nullable(),
    primarySheetWinch: z.string().optional().nullable(),
    secondarySheetWinch: z.string().optional().nullable(),
    genoaSheetwinches: z.string().optional().nullable(),
    halyardWinches: z.string().optional().nullable(),
    multifunctionalWinches: z.string().optional().nullable(),
    spiPole: z.string().optional().nullable(),
  }).optional().nullable(),

  // Machinery
  machinery: z.object({
    numberOfEngines: z.coerce.number().optional().nullable(),
    make: z.string().optional().nullable(),
    type: z.string().optional().nullable(),
    hp: z.coerce.number().optional().nullable(),
    kw: z.coerce.number().optional().nullable(),
    fuel: z.string().optional().nullable(),
    yearInstalled: z.coerce.number().optional().nullable(),
    yearOfOverhaul: z.string().optional().nullable(),
    maxSpeedKnots: z.coerce.number().optional().nullable(),
    cruisingSpeedKnots: z.coerce.number().optional().nullable(),
    consumptionLhr: z.coerce.number().optional().nullable(),
    engineCoolingSystem: z.string().optional().nullable(),
    drive: z.string().optional().nullable(),
    shaftSeal: z.string().optional().nullable(),
    engineControls: z.string().optional().nullable(),
    gearbox: z.string().optional().nullable(),
    bowthruster: z.string().optional().nullable(),
    propellerType: z.string().optional().nullable(),
    manualBilgePump: z.string().optional().nullable(),
    electricBilgePump: z.string().optional().nullable(),
    electricalInstallation: z.string().optional().nullable(),
    generator: z.string().optional().nullable(),
    batteries: z.string().optional().nullable(),
    startBattery: z.string().optional().nullable(),
    serviceBattery: z.string().optional().nullable(),
    batteryMonitor: z.string().optional().nullable(),
    batteryCharger: z.string().optional().nullable(),
    solarPanel: z.string().optional().nullable(),
    shorepower: z.string().optional().nullable(),
    watermaker: z.string().optional().nullable(),
    extraInfo: z.string().optional().nullable(),
  }).optional().nullable(),

  // Navigation
  navigation: z.object({
    compass: z.string().optional().nullable(),
    depthSounder: z.string().optional().nullable(),
    log: z.string().optional().nullable(),
    windset: z.string().optional().nullable(),
    vhf: z.string().optional().nullable(),
    autopilot: z.string().optional().nullable(),
    radar: z.string().optional().nullable(),
    gps: z.string().optional().nullable(),
    plotter: z.string().optional().nullable(),
    navtex: z.string().optional().nullable(),
    aisTransceiver: z.string().optional().nullable(),
    navigationLights: z.string().optional().nullable(),
    extraInfo: z.string().optional().nullable(),
  }).optional().nullable(),
  
  equipment: z.object({
    fixedWindscreen: z.string().optional().nullable(),
    cockpitTable: z.string().optional().nullable(),
    bathingPlatform: z.string().optional().nullable(),
    boardingLadder: z.string().optional().nullable(),
    deckShower: z.string().optional().nullable(),
    anchor: z.string().optional().nullable(),
    anchorChain: z.string().optional().nullable(),
    anchor2: z.string().optional().nullable(),
    windlass: z.string().optional().nullable(),
    deckWash: z.string().optional().nullable(),
    dinghy: z.string().optional().nullable(),
    outboard: z.string().optional().nullable(),
    davits: z.string().optional().nullable(),
    seaRailing: z.string().optional().nullable(),
    pushpit: z.string().optional().nullable(),
    pulpit: z.string().optional().nullable(),
    lifebuoy: z.string().optional().nullable(),
    radarReflector: z.string().optional().nullable(),
    fenders: z.string().optional().nullable(),
    mooringLines: z.string().optional().nullable(),
    radio: z.string().optional().nullable(),
    cockpitSpeakers: z.string().optional().nullable(),
    speakersInSalon: z.string().optional().nullable(),
    fireExtinguisher: z.string().optional().nullable(),
  }).optional().nullable(),

  // Indication Ratios
  saDisp: z.coerce.number().optional().nullable(),
  balDisp: z.coerce.number().optional().nullable(),
  dispLen: z.coerce.number().optional().nullable(),
  comfortRatio: z.coerce.number().optional().nullable(),
  capsizeScreeningFormula: z.coerce.number().optional().nullable(),
  sNum: z.coerce.number().optional().nullable(),
  hullSpeed: z.coerce.number().optional().nullable(),
  poundsPerInchImmersion: z.coerce.number().optional().nullable(),

  // Added missing fields
  status: z.string().optional(),
  vat: z.string().optional(),
  salesOffice: z.string().optional(),
});

// De Valk aligned schema - exact field mapping
export const devalkSellFormSchema = z.object({
  // Key Details (exactly as De Valk presents them)
  keyDetails: z.object({
    dimensions: z.string().optional(),
    material: z.string().optional(),
    built: z.string().optional(),
    engines: z.string().optional(),
    hpKw: z.string().optional(),
    lying: z.string().optional(),
    salesOffice: z.string().optional(),
    status: z.string().optional(),
    vat: z.string().optional(),
    askingPrice: z.string().optional(),
  }),
  
  // General Information (exactly as De Valk presents them)
  generalInfo: z.object({
    model: z.string().optional(),
    type: z.string().optional(),
    loaM: z.string().optional(),
    lwlM: z.string().optional(),
    beamM: z.string().optional(),
    draftM: z.string().optional(),
    airDraftM: z.string().optional(),
    headroomM: z.string().optional(),
    yearBuilt: z.string().optional(),
    builder: z.string().optional(),
    country: z.string().optional(),
    designer: z.string().optional(),
    displacementT: z.string().optional(),
    ballastTonnes: z.string().optional(),
    hullMaterial: z.string().optional(),
    hullColour: z.string().optional(),
    hullShape: z.string().optional(),
    keelType: z.string().optional(),
    superstructureMaterial: z.string().optional(),
    deckMaterial: z.string().optional(),
    deckFinish: z.string().optional(),
    superstructureDeckFinish: z.string().optional(),
    cockpitDeckFinish: z.string().optional(),
    dorades: z.string().optional(),
    windowFrame: z.string().optional(),
    windowMaterial: z.string().optional(),
    deckHatch: z.string().optional(),
    fuelTankLitre: z.string().optional(),
    levelIndicatorFuelTank: z.string().optional(),
    freshwaterTankLitre: z.string().optional(),
    levelIndicatorFreshwater: z.string().optional(),
    wheelSteering: z.string().optional(),
    outsideHelmPosition: z.string().optional(),
  }),
  
  // Accommodation (exactly as De Valk presents them)
  accommodation: z.object({
    cabins: z.string().optional(),
    berths: z.string().optional(),
    interior: z.string().optional(),
    layout: z.string().optional(),
    floor: z.string().optional(),
    openCockpit: z.string().optional(),
    aftDeck: z.string().optional(),
    saloon: z.string().optional(),
    headroomSalonM: z.string().optional(),
    heating: z.string().optional(),
    navigationCenter: z.string().optional(),
    chartTable: z.string().optional(),
    galley: z.string().optional(),
    countertop: z.string().optional(),
    sink: z.string().optional(),
    cooker: z.string().optional(),
    oven: z.string().optional(),
    microwave: z.string().optional(),
    fridge: z.string().optional(),
    freezer: z.string().optional(),
    hotWaterSystem: z.string().optional(),
    waterPressureSystem: z.string().optional(),
    ownersCabin: z.string().optional(),
    bedLengthM: z.string().optional(),
    wardrobe: z.string().optional(),
    bathroom: z.string().optional(),
    toilet: z.string().optional(),
    toiletSystem: z.string().optional(),
    washBasin: z.string().optional(),
    shower: z.string().optional(),
    guestCabin1: z.string().optional(),
    bedLengthM1: z.string().optional(),
    wardrobe1: z.string().optional(),
    guestCabin2: z.string().optional(),
    bedLengthM2: z.string().optional(),
    wardrobe2: z.string().optional(),
    bathroom2: z.string().optional(),
    toilet2: z.string().optional(),
    toiletSystem2: z.string().optional(),
    washBasin2: z.string().optional(),
    shower2: z.string().optional(),
    washingMachine: z.string().optional(),
  }),
  
  // Machinery (exactly as De Valk presents them)
  machinery: z.object({
    noOfEngines: z.string().optional(),
    make: z.string().optional(),
    type: z.string().optional(),
    hp: z.string().optional(),
    kw: z.string().optional(),
    fuel: z.string().optional(),
    yearInstalled: z.string().optional(),
    yearOfOverhaul: z.string().optional(),
    maximumSpeedKn: z.string().optional(),
    cruisingSpeedKn: z.string().optional(),
    consumptionLhr: z.string().optional(),
    engineCoolingSystem: z.string().optional(),
    drive: z.string().optional(),
    shaftSeal: z.string().optional(),
    engineControls: z.string().optional(),
    gearbox: z.string().optional(),
    bowthruster: z.string().optional(),
    propellerType: z.string().optional(),
    manualBilgePump: z.string().optional(),
    electricBilgePump: z.string().optional(),
    electricalInstallation: z.string().optional(),
    generator: z.string().optional(),
    batteries: z.string().optional(),
    startBattery: z.string().optional(),
    serviceBattery: z.string().optional(),
    batteryMonitor: z.string().optional(),
    batteryCharger: z.string().optional(),
    solarPanel: z.string().optional(),
    shorepower: z.string().optional(),
    watermaker: z.string().optional(),
    extraInfo: z.string().optional(),
  }),
  
  // Navigation (exactly as De Valk presents them)
  navigation: z.object({
    compass: z.string().optional(),
    electricCompass: z.string().optional(),
    depthSounder: z.string().optional(),
    log: z.string().optional(),
    windset: z.string().optional(),
    repeater: z.string().optional(),
    vhf: z.string().optional(),
    vhfHandheld: z.string().optional(),
    autopilot: z.string().optional(),
    rudderAngleIndicator: z.string().optional(),
    radar: z.string().optional(),
    plotterGps: z.string().optional(),
    electronicCharts: z.string().optional(),
    aisTransceiver: z.string().optional(),
    epirb: z.string().optional(),
    navigationLights: z.string().optional(),
    extraInfo: z.string().optional(),
  }),
  
  // Equipment (exactly as De Valk presents them)
  equipment: z.object({
    fixedWindscreen: z.string().optional(),
    cockpitTable: z.string().optional(),
    bathingPlatform: z.string().optional(),
    boardingLadder: z.string().optional(),
    deckShower: z.string().optional(),
    anchor: z.string().optional(),
    anchorChain: z.string().optional(),
    anchor2: z.string().optional(),
    windlass: z.string().optional(),
    deckWash: z.string().optional(),
    dinghy: z.string().optional(),
    outboard: z.string().optional(),
    davits: z.string().optional(),
    seaRailing: z.string().optional(),
    pushpit: z.string().optional(),
    pulpit: z.string().optional(),
    lifebuoy: z.string().optional(),
    radarReflector: z.string().optional(),
    fenders: z.string().optional(),
    mooringLines: z.string().optional(),
    radio: z.string().optional(),
    cockpitSpeakers: z.string().optional(),
    speakersInSalon: z.string().optional(),
    fireExtinguisher: z.string().optional(),
  }),
  
  // Rigging (exactly as De Valk presents them)
  rigging: z.object({
    rigging: z.string().optional(),
    standingRigging: z.string().optional(),
    brandMast: z.string().optional(),
    materialMast: z.string().optional(),
    spreaders: z.string().optional(),
    mainsail: z.string().optional(),
    stowayMast: z.string().optional(),
    cutterstay: z.string().optional(),
    jib: z.string().optional(),
    genoa: z.string().optional(),
    genoaFurler: z.string().optional(),
    cutterFurler: z.string().optional(),
    gennaker: z.string().optional(),
    spinnaker: z.string().optional(),
    reefingSystem: z.string().optional(),
    backstayAdjuster: z.string().optional(),
    primarySheetWinch: z.string().optional(),
    secondarySheetWinch: z.string().optional(),
    genoaSheetwinches: z.string().optional(),
    halyardWinches: z.string().optional(),
    multifunctionalWinches: z.string().optional(),
    spiPole: z.string().optional(),
  }),
  
  // Indication Ratios (exactly as De Valk presents them)
  indicationRatios: z.object({
    saDispl: z.string().optional(),
    balDispl: z.string().optional(),
    dispLen: z.string().optional(),
    comfortRatio: z.string().optional(),
    capsizeScreeningFormula: z.string().optional(),
    s: z.string().optional(),
    hullSpeed: z.string().optional(),
    poundsInchImmersion: z.string().optional(),
  }),
  
  // Keep existing fields for compatibility
  title: z.string().optional(),
  make: z.string().optional(),
  model: z.string().optional(),
  year: z.coerce.number().optional().nullable(),
  length: z.coerce.number().optional().nullable(),
  price: z.coerce.number().optional().nullable(),
  description: z.string().optional(),
  heroImage: z.any().optional(),
  galleryImages: z.array(z.any()).optional(),
  listingType: z.string().optional(),
  boatType: z.string().optional(),
  condition: z.string().optional(),
  location: z.string().optional(),
  fuelType: z.string().optional(),
  hullMaterial: z.string().optional(),
  transomShape: z.string().optional(),
  bowShape: z.string().optional(),
  keelType: z.string().optional(),
  rudderType: z.string().optional(),
  propellerType: z.string().optional(),
  sailRigging: z.string().optional(),
  features: z.array(z.string()).optional(),
  divisions: z.array(z.string()).optional(),
  deck: z.array(z.string()).optional(),
  otherSpecifications: z.string().optional(),
});

export type DeValkFormValues = z.infer<typeof devalkSellFormSchema>;
