export type Yacht = {
  id: string;
  name: string;
  price: number;
  year: number;
  length: number; // in feet
  location: string;
  locationId?: string;
  imageUrl: string;
  imageHint: string;
  images?: string[];
  make: string;
  model: string;
  listingType: 'Private' | 'Broker';
  boatType: 'Sailing' | 'Catamaran' | string;
  condition: 'New' | 'Used' | string;
  description?: string;
  fuelType?: string;
  hullMaterial?: string;
  hullShape?: string;
  bowShape?: string;
  keelType?: string;
  rudderType?: string;
  propellerType?: string;
  usageStyles?: string[];
  features?: string[];
  deck?: string[];
  cabin?: string[];
  otherSpecifications?: string;
};
